// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIAccordion is a component that creates a list of items that can be shown individually by clicking an item's header.
type UIAccordion interface {
	app.UI

	// Class adds a CSS class to the accordion.
	Class(v string) UIAccordion

	// Content sets the main content.
	Content(elems ...app.UI) UIAccordion

	// Option sets a component option.
	Option(k string, v interface{}) UIAccordion
}

type accordion struct {
	app.Compo

	Iclass   string
	Icontent []app.UI

	Ioptions map[string]interface{}
}

// Accordion returns a accordion component.
func Accordion() UIAccordion {
	return &accordion{}
}

func (a *accordion) Class(v string) UIAccordion {
	if a.Iclass != "" {
		a.Iclass += " "
	}

	a.Iclass += v
	return a
}

func (a *accordion) Content(elems ...app.UI) UIAccordion {
	a.Icontent = app.FilterUIElems(elems...)
	return a
}

func (a *accordion) Option(k string, v interface{}) UIAccordion {
	if a.Ioptions == nil {
		a.Ioptions = make(map[string]interface{}, 0)
	}
	a.Ioptions[k] = v
	return a
}

func (a *accordion) Render() app.UI {
	opts, _ := JSONString(a.Ioptions)

	return app.Ul().
		DataSet("uk-accordion", opts).
		Class(a.Iclass).
		Body(a.Icontent...)
}
