// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIArticle is a component that consists of the article itself, a title and meta data
type UIArticle interface {
	app.UI

	// Class adds a CSS class to the article.
	Class(v string) UIArticle

	// Content sets the main content.
	Content(elems ...app.UI) UIArticle
}

type article struct {
	app.Compo

	Iclass   string
	Icontent []app.UI
}

// Article returns a article component.
func Article() UIArticle {
	return &article{
		Iclass: "uk-article",
	}
}

func (a *article) Class(v string) UIArticle {
	if a.Iclass != "" {
		a.Iclass += " "
	}

	a.Iclass += v
	return a
}

func (a *article) Content(elems ...app.UI) UIArticle {
	a.Icontent = app.FilterUIElems(elems...)
	return a
}

func (a *article) Render() app.UI {
	return app.Article().
		Class(a.Iclass).
		Body(a.Icontent...)
}
