// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIBreadcrumb is a component that creates breadcrumbs to show users their location within a website
type UIBreadcrumb interface {
	app.UI

	// Class adds a CSS class to the breadcrumb.
	Class(v string) UIBreadcrumb

	// Content sets the main content.
	Content(elems ...app.UI) UIBreadcrumb
}

type breadcrumb struct {
	app.Compo

	Iclass   string
	Icontent []app.UI
}

// Breadcrumb returns a breadcrumb component.
func Breadcrumb() UIBreadcrumb {
	return &breadcrumb{
		Iclass: "uk-breadcrumb",
	}
}

func (b *breadcrumb) Class(v string) UIBreadcrumb {
	if b.Iclass != "" {
		b.Iclass += " "
	}

	b.Iclass += v
	return b
}

func (b *breadcrumb) Content(elems ...app.UI) UIBreadcrumb {
	b.Icontent = app.FilterUIElems(elems...)
	return b
}

func (b *breadcrumb) Render() app.UI {
	return app.Ul().
		Class(b.Iclass).
		Body(b.Icontent...)
}
