// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIButton is a component that creates nice looking buttons, which come in different styles
type UIButton interface {
	app.UI

	// Class adds a CSS class to the button.
	Class(v string) UIButton

	// Content sets the main content.
	Content(elems ...app.UI) UIButton

	// Danger indicates a dangerous or negative action.
	Danger() UIButton

	// Default button style.
	Default() UIButton

	// FullWidth fills 100% of the available width.
	FullWidth() UIButton

	// Large makes a <button> look larger.
	Large() UIButton

	// Link makes a <button> look like an <a> element.
	Link() UIButton

	// Primary indicates the primary action.
	Primary() UIButton

	// Secondary indicates an important action.
	Secondary() UIButton

	// Small makes a <button> look smaller.
	Small() UIButton

	// Text applies an alternative, typographic style.
	Text() UIButton
}

type button struct {
	app.Compo

	Iclass   string
	Icontent []app.UI
}

// Button returns a button component.
func Button() UIButton {
	return &button{
		Iclass: "uk-button",
	}
}

func (b *button) Class(v string) UIButton {
	if b.Iclass != "" {
		b.Iclass += " "
	}

	b.Iclass += v
	return b
}

func (b *button) Content(elems ...app.UI) UIButton {
	b.Icontent = app.FilterUIElems(elems...)
	return b
}

func (b *button) Danger() UIButton {
	b.Class("uk-button-danger")
	return b
}

func (b *button) Default() UIButton {
	b.Class("uk-button-default")
	return b
}

func (b *button) FullWidth() UIButton {
	b.Class("uk-width-1-1")
	return b
}

func (b *button) Large() UIButton {
	b.Class("uk-button-large")
	return b
}

func (b *button) Link() UIButton {
	b.Class("uk-button-link")
	return b
}

func (b *button) Primary() UIButton {
	b.Class("uk-button-primary")
	return b
}

func (b *button) Secondary() UIButton {
	b.Class("uk-button-secondary")
	return b
}

func (b *button) Small() UIButton {
	b.Class("uk-button-small")
	return b
}

func (b *button) Text() UIButton {
	b.Class("uk-button-text")
	return b
}

func (b *button) Render() app.UI {
	return app.Button().
		Class(b.Iclass).
		Body(b.Icontent...)
}
