// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIContainer is a component that allows you to align and center your page content
type UIContainer interface {
	app.UI

	// Class adds a CSS class to the container.
	Class(v string) UIContainer

	// Content sets the main content.
	Content(elems ...app.UI) UIContainer

	// Expand if you do not want to limit the container width but still want the dynamic horizontal padding.
	Expand() UIContainer

	// Large for a large container.
	Large() UIContainer

	// Small for a small container.
	Small() UIContainer

	// XLarge for a xlarge container.
	XLarge() UIContainer

	// XSmall for a xsmall container.
	XSmall() UIContainer
}

type container struct {
	app.Compo

	Iclass   string
	Icontent []app.UI
}

// Container returns a container component.
func Container() UIContainer {
	return &container{
		Iclass: "uk-container",
	}
}

func (c *container) Class(v string) UIContainer {
	if c.Iclass != "" {
		c.Iclass += " "
	}

	c.Iclass += v
	return c
}

func (c *container) Content(elems ...app.UI) UIContainer {
	c.Icontent = app.FilterUIElems(elems...)
	return c
}

func (c *container) Expand() UIContainer {
	c.Class("uk-container-expand")
	return c
}

func (c *container) Large() UIContainer {
	c.Class("uk-container-large")
	return c
}

func (c *container) Small() UIContainer {
	c.Class("uk-container-small")
	return c
}

func (c *container) XLarge() UIContainer {
	c.Class("uk-container-xlarge")
	return c
}

func (c *container) XSmall() UIContainer {
	c.Class("uk-container-xsmall")
	return c
}

func (c *container) Render() app.UI {
	return app.Div().
		Class(c.Iclass).
		Body(c.Icontent...)
}
