// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UIGrid is a component that creates a fully responsive, fluid and nestable grid layout
type UIGrid interface {
	app.UI

	// Class adds a CSS class to the grid.
	Class(v string) UIGrid

	// Content sets the main content.
	Content(elems ...app.UI) UIGrid

	// Option sets a component option.
	Option(k string, v interface{}) UIGrid

	// Collapse to remove the grid gap entirely.
	Collapse() UIGrid

	// Divider to separate grid cells with lines.
	Divider() UIGrid

	// Large to apply a large gap with breakpoints.
	Large() UIGrid

	// MatchHeight to match the height of the direct child of each cell.
	MatchHeight() UIGrid

	// Medium to apply a medium gap like the default one, but without a breakpoint.
	Medium() UIGrid

	// Small to apply a small gap.
	Small() UIGrid
}

type grid struct {
	app.Compo

	Iclass   string
	Icontent []app.UI

	Ioptions map[string]interface{}
}

// Grid returns a grid component.
func Grid() UIGrid {
	return &grid{}
}

func (g *grid) Class(v string) UIGrid {
	if g.Iclass != "" {
		g.Iclass += " "
	}

	g.Iclass += v
	return g
}

func (g *grid) Content(elems ...app.UI) UIGrid {
	g.Icontent = app.FilterUIElems(elems...)
	return g
}

func (g *grid) Option(k string, v interface{}) UIGrid {
	if g.Ioptions == nil {
		g.Ioptions = make(map[string]interface{}, 0)
	}
	g.Ioptions[k] = v
	return g
}

func (g *grid) Collapse() UIGrid {
	g.Class("uk-grid-collapse")
	return g
}

func (g *grid) Divider() UIGrid {
	g.Class("uk-grid-divider")
	return g
}

func (g *grid) Large() UIGrid {
	g.Class("uk-grid-large")
	return g
}

func (g *grid) MatchHeight() UIGrid {
	g.Class("uk-grid-match")
	return g
}

func (g *grid) Medium() UIGrid {
	g.Class("uk-grid-medium")
	return g
}

func (g *grid) Small() UIGrid {
	g.Class("uk-grid-small")
	return g
}

func (g *grid) Render() app.UI {
	opts, _ := JSONString(g.Ioptions)

	return app.Div().
		DataSet("uk-grid", opts).
		Class(g.Iclass).
		Body(g.Icontent...)
}
