// Code generated by go generate; DO NOT EDIT.

package uikit

import (
	"github.com/maxence-charriere/go-app/v9/pkg/app"
)

// UISection is a component that creates horizontal layout sections with different background colors and styles
type UISection interface {
	app.UI

	// Class adds a CSS class to the section.
	Class(v string) UISection

	// Content sets the main content.
	Content(elems ...app.UI) UISection

	// Default adds the default background color of your site.
	Default() UISection

	// Large to increase a section's padding.
	Large() UISection

	// Muted adds a muted background color.
	Muted() UISection

	// Primary adds a primary background color.
	Primary() UISection

	// RemoveVerticalPadding removes top and bottom padding from an element.
	RemoveVerticalPadding() UISection

	// Secondary adds a secondary background color.
	Secondary() UISection

	// Small to decrease a section's padding.
	Small() UISection

	// XLarge to further increase a section's padding.
	XLarge() UISection

	// XSmall to decrease a section's padding to a minimum.
	XSmall() UISection
}

type section struct {
	app.Compo

	Iclass   string
	Icontent []app.UI
}

// Section returns a section component.
func Section() UISection {
	return &section{
		Iclass: "uk-section",
	}
}

func (s *section) Class(v string) UISection {
	if s.Iclass != "" {
		s.Iclass += " "
	}

	s.Iclass += v
	return s
}

func (s *section) Content(elems ...app.UI) UISection {
	s.Icontent = app.FilterUIElems(elems...)
	return s
}

func (s *section) Default() UISection {
	s.Class("uk-section-default")
	return s
}

func (s *section) Large() UISection {
	s.Class("uk-section-large")
	return s
}

func (s *section) Muted() UISection {
	s.Class("uk-section-muted")
	return s
}

func (s *section) Primary() UISection {
	s.Class("uk-section-primary")
	return s
}

func (s *section) RemoveVerticalPadding() UISection {
	s.Class("uk-padding-remove-vertical")
	return s
}

func (s *section) Secondary() UISection {
	s.Class("uk-section-secondary")
	return s
}

func (s *section) Small() UISection {
	s.Class("uk-section-small")
	return s
}

func (s *section) XLarge() UISection {
	s.Class("uk-section-xlarge")
	return s
}

func (s *section) XSmall() UISection {
	s.Class("uk-section-xsmall")
	return s
}

func (s *section) Render() app.UI {
	return app.Div().
		Class(s.Iclass).
		Body(s.Icontent...)
}
